import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './_components/header'
import { Footer } from './_components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'prestigeconstructions.ltd',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} dark:bg-slate-900 flex flex-col h-full`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
